import re

player_dict = {
    "Fred": "Frederico Rodrigues de Paula Santos",
    "Ki Sung-yueng": "Sung-yueng Ki",
    "Solly March": "Solomon March",
    "Jonny": "Jonathan Castro Otto",
    "Felipe Anderson": "Felipe Anderson Pereira Gomes",
    "Mat Ryan": "Mathew Ryan",
    "Kenedy": "Robert Kenedy Nunes do Nascimento",
    "Jorginho": "Jorge Luiz Frello Filho",
    "Bernard": "Bernard Anício Caldeira Duarte",
    "Romain Saiss": "Romain Saïss",
    "Bernardo Silva": "Bernardo Mota Veiga de Carvalho e Silva",
    "N&#039;Golo Kanté": "N'Golo Kanté",
    "João Moutinho": "João Filipe Iria Santos Moutinho",
    "Franck Zambo": "André-Frank Zambo Anguissa",
    "Fousseni Diabate": "Fousseni Diabaté",
    "Jazz Richards": "Ashley Darel Jazz Richards",
    "Danilo": "Danilo Luiz da Silva",
    "Richarlison": "Richarlison de Andrade",
    "Bernardo": "Bernardo Fernandes da Silva Junior",
    "Fernandinho": "Fernando Luiz Rosa",
    "Joselu": "Jose Luis Mato Sanmartín",
    "Son Heung-Min": "Heung-Min Son",
    "Diogo Dalot": "José Diogo Dalot Teixeira",
    "José Izquierdo": "José Heriberto Izquierdo Mena",
    "Fabri": "Fabricio Agosto Ramírez",
    "Eddie Nketiah": "Edward Nketiah",
    "Rui Patrício": "Rui Pedro dos Santos Patrício",
    "Greg Cunningham": "Greg Cunninghamm",
    "Junior Hoilett": "David Junior Hoilett",
    "Isaac Success": "Isaac Success Ajayi",
    "Xande Silva": "Alexandre Nascimento Costa Silva",
    "Bruno": "Bruno Saltor Grau",
    "Léo Bonatini": "Bonatini Lohner Maia Bonatini",
    "André Gomes": "André Filipe Tavares Gomes",
    "Kiko Femenía": "Francisco Femenía Far",
    "Dele Alli": "Bamidele Alli",
    "Ricardo Pereira": "Ricardo Domingos Barbosa Pereira",
    "Sokratis": "Sokratis Papastathopoulos",
    "Alisson": "Alisson Ramses Becker",
    "Fabinho": "Fabio Henrique Tavares",
    "Adrien Silva": "Adrien Sebastian Perruchet Silva",
    "David de Gea": "David De Gea",
    "Gabriel Jesus": "Gabriel Fernando de Jesus",
    "Pedro": "Pedro Rodríguez Ledesma",
    "Zanka": "Mathias Jorgensen",
    "David Luiz": "David Luiz Moreira Marinho",
    "Rúben Neves": "Rúben Diogo da Silva Neves",
    "Ben Chilwell": "Benjamin Chilwell",
    "Kepa": "Kepa Arrizabalaga",
    "Emerson": "Emerson Palmieri dos Santos",
    "Ederson": "Ederson Santana de Moraes",
    "Chicharito": "Javier Hernández Balcázar",
    "Rúben Vinagre": "Rúben Gonçalo Silva Nascimento Vinagre",
    "Oriol Romeu": "Oriol Romeu Vidal",
    "Lucas Moura": "Lucas Rodrigues Moura da Silva",
    "Willian": "Willian Borges Da Silva",
}

team_dict = {
    "Manchester City": "Man City",
    "Tottenham": "Spurs",
    "Manchester United": "Man Utd",
    "Wolverhampton Wanderers": "Wolves"
}

desired_attributes = [
    "xG",
    "xA",
    "key_passes",
    "npg",
    "npxG",
    "xGChain",
    "xGBuildup",
    "shots",
    "understat_history"
]

versus_pattern = re.compile(r"!fplbot\s+([^\W\d_]+)\s+(?:vs.|vs)\s+([a-zA-Z ]+)")
